# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: node-hello-world
spec:
  selector:
    app: node-hello-world
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3000
  type: LoadBalancer
